#!/usr/bin/env python3
"""Plot arXiv GLIN Fig.17-style hybrid workload curves."""

import argparse
import csv
import os
from collections import defaultdict
from pathlib import Path

os.environ.setdefault("MPLCONFIGDIR", "/tmp/matplotlib")

import matplotlib.pyplot as plt


INDEX_LABELS = {
    "GLIN_PIECEWISE": "GLIN-piecewise",
    "GLIN_LSM_ASYNC": "GLIN-LSM-async",
    "GLIN_LSM_SEGMENTED": "GLIN-LSM-segmented",
    "GLIN_LSM_SEGMENTED4": "GLIN-LSM-seg4",
    "GLIN_LSM_BG": "GLIN-LSM-bg",
    "Boost_Rtree": "Boost R-tree",
    "GEOS_Quadtree": "Quadtree",
}

INDEX_ORDER = [
    "GLIN_PIECEWISE",
    "GLIN_LSM_ASYNC",
    "GLIN_LSM_SEGMENTED",
    "GLIN_LSM_SEGMENTED4",
    "GLIN_LSM_BG",
    "GEOS_Quadtree",
    "Boost_Rtree",
]

STYLE = {
    "GLIN_PIECEWISE": {"marker": "o", "linestyle": "-", "color": "#1f77b4"},
    "GLIN_LSM_ASYNC": {"marker": "D", "linestyle": "-.", "color": "#9467bd"},
    "GLIN_LSM_SEGMENTED": {"marker": "P", "linestyle": "-", "color": "#8c564b"},
    "GLIN_LSM_SEGMENTED4": {"marker": "X", "linestyle": "--", "color": "#ff7f0e"},
    "GLIN_LSM_BG": {"marker": "v", "linestyle": "-", "color": "#17becf"},
    "GEOS_Quadtree": {"marker": "s", "linestyle": "--", "color": "#d62728"},
    "Boost_Rtree": {"marker": "^", "linestyle": ":", "color": "#2ca02c"},
}

WORKLOAD_LABELS = {
    "read_intensive": "Read-intensive",
    "write_intensive": "Write-intensive",
}


def parse_args():
    parser = argparse.ArgumentParser(
        description="Plot Fig.17 hybrid workload curves from progress CSV."
    )
    parser.add_argument(
        "--input_csv",
        default="results/fig17_hybrid_1m/fig17_hybrid_progress.csv",
        help="Input progress CSV generated by bench_hybrid_wkt_piece.",
    )
    parser.add_argument(
        "--output_dir",
        default="figures/fig17_hybrid_1m",
        help="Directory for output figures.",
    )
    parser.add_argument("--prefix", default="fig17_hybrid", help="Output prefix.")
    return parser.parse_args()


def read_rows(path):
    rows = []
    with open(path, newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            try:
                row["inserted_percent"] = float(row["inserted_percent"])
                row["throughput_transactions_per_sec"] = float(
                    row["throughput_transactions_per_sec"]
                )
            except (KeyError, ValueError) as exc:
                raise ValueError(f"Bad row in {path}: {row}") from exc
            rows.append(row)
    if not rows:
        raise ValueError(f"No rows loaded from {path}")
    return rows


def group_rows(rows):
    grouped = defaultdict(list)
    for row in rows:
        key = (row["workload"], row["dataset"], row["index"])
        grouped[key].append(row)
    for key in grouped:
        grouped[key].sort(key=lambda row: row["inserted_percent"])
    return grouped


def ordered_values(rows, field):
    return [row[field] for row in rows]


def plot_panel(rows, output_path):
    grouped = group_rows(rows)
    datasets = [d for d in ["ROADS", "PARKS"] if any(row["dataset"] == d for row in rows)]
    if not datasets:
        datasets = sorted({row["dataset"] for row in rows})
    workloads = [
        w
        for w in ["read_intensive", "write_intensive"]
        if any(row["workload"] == w for row in rows)
    ]
    if not workloads:
        workloads = sorted({row["workload"] for row in rows})

    fig, axes = plt.subplots(
        len(workloads),
        len(datasets),
        figsize=(5.2 * len(datasets), 3.8 * len(workloads)),
        squeeze=False,
    )

    for r, workload in enumerate(workloads):
        for c, dataset in enumerate(datasets):
            ax = axes[r][c]
            for index in INDEX_ORDER:
                series = grouped.get((workload, dataset, index), [])
                if not series:
                    continue
                ax.plot(
                    ordered_values(series, "inserted_percent"),
                    ordered_values(series, "throughput_transactions_per_sec"),
                    label=INDEX_LABELS.get(index, index),
                    linewidth=1.8,
                    markersize=4.5,
                    **STYLE.get(index, {}),
                )
            ax.set_title(f"{WORKLOAD_LABELS.get(workload, workload)} on {dataset}")
            ax.set_xlabel("Number of Inserted Records (%)")
            ax.set_ylabel("Throughput (Transactions/sec)")
            ax.grid(True, axis="y", linestyle=":", linewidth=0.8, alpha=0.7)
            ax.set_xlim(left=0)
            ax.legend(frameon=False, fontsize=9)

    fig.tight_layout()
    fig.savefig(output_path, dpi=220)
    plt.close(fig)


def plot_each_workload(rows, output_dir, prefix):
    grouped = group_rows(rows)
    for workload in sorted({row["workload"] for row in rows}):
        for dataset in sorted({row["dataset"] for row in rows}):
            fig, ax = plt.subplots(figsize=(6.2, 4.2))
            for index in INDEX_ORDER:
                series = grouped.get((workload, dataset, index), [])
                if not series:
                    continue
                ax.plot(
                    ordered_values(series, "inserted_percent"),
                    ordered_values(series, "throughput_transactions_per_sec"),
                    label=INDEX_LABELS.get(index, index),
                    linewidth=1.8,
                    markersize=4.5,
                    **STYLE.get(index, {}),
                )
            ax.set_title(f"{WORKLOAD_LABELS.get(workload, workload)} on {dataset}")
            ax.set_xlabel("Number of Inserted Records (%)")
            ax.set_ylabel("Throughput (Transactions/sec)")
            ax.grid(True, axis="y", linestyle=":", linewidth=0.8, alpha=0.7)
            ax.legend(frameon=False)
            fig.tight_layout()
            out = output_dir / f"{prefix}_{workload}_{dataset}.png"
            fig.savefig(out, dpi=220)
            plt.close(fig)


def main():
    args = parse_args()
    input_csv = Path(args.input_csv)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    rows = read_rows(input_csv)
    panel_path = output_dir / f"{args.prefix}_curves_panel.png"
    plot_panel(rows, panel_path)
    plot_each_workload(rows, output_dir, args.prefix)

    print(f"Rows: {len(rows)}")
    print(f"Panel: {panel_path}")


if __name__ == "__main__":
    main()
